eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test1?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password:
  application:
    name: order
  jpa:
    show-sql: true

server:
  port: 8093
dev: dev
